[colors]
draw_bold_text_with_bright_colors = true

# [env]
# TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Propo"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[window]
opacity = 0.7
blur = true

[window.padding]
x = 10
y = 10

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[general]
live_config_reload = true
import = [
	# "~/.config/alacritty/rose-pine.toml",
	"~/.config/alacritty/catppuccin/catppuccin-frappe.toml",
]


[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

# [colors.normal]
# black = "#373b41"
# blue = "#afecff"
# cyan = "#8abeb7"
# green = "#c0ff78"
# magenta = "#b294bb"
# red = "#ffa3be"
# white = "#ebe5d4"
# yellow = "#ffb050"
#
# [colors.bright]
# black = "#282a2e"
# blue = "#37424f"
# cyan = "#00433a"
# green = "#32421f"
# magenta = "#310042"
# red = "#42001b"
# white = "#707880"
# yellow = "#422800"
#
