#!/bin/sh
Selection=true

xrdb -merge ~/.Xresources
setxkbmap de
xmodmap ~/.Xmodmap
clipmenud &
xsetroot -cursor_name leftptr &
picom --daemon &
light -I &
light -N 2 &

conky -c ~/.config/conky/conky_task_progress.lua &
conky -c ~/.config/conky/conky.lua &



# Auto lock after inactive

xset s 300 5 &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock &


# source /etc/profile does not have any effect



export BROWSER=chromium-bin
export EDITOR=nvim

exec dbus-launch $@
