#! /bin/sh

bash /home/niklas/.local/scripts/startup.sh &
####  ##
##  ##  ##
####  ##

#bspc monitor eDP-1 -d 1 2 3 4 5
#bspc monitor HDMI-2 -d 6 7 8 9 0

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0 HDMI-1

#bspc monitor eDP-1 -d 1 2 3 4 5 
#bspc monitor HDMI-2 -d 6 7 8 9 0
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a FAlacritty rectangle=1576x925+0+0 center=true state=floating
